# Generated by Django 4.1.1 on 2022-09-19 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('professor', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15)),
                ('week', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=10)),
                ('professor', models.CharField(max_length=150)),
                ('points', models.PositiveSmallIntegerField()),
                ('subject', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='seminar', to='college.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15)),
                ('week', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=10)),
                ('professor', models.CharField(max_length=150)),
                ('points', models.PositiveSmallIntegerField()),
                ('subject', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab', to='college.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15)),
                ('week', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=10)),
                ('points', models.PositiveSmallIntegerField(blank=True)),
                ('subject', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='college.subject')),
            ],
        ),
    ]
