# Generated by Django 4.1.1 on 2022-09-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='credit_points',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
