# Generated by Django 4.1.1 on 2022-09-22 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_alter_course_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='college.subject'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='seminars', to='college.subject'),
        ),
    ]
