# Generated by Django 4.1.1 on 2022-09-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_alter_lab_subject_alter_seminar_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='nr',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
