# Generated by Django 4.1.1 on 2022-09-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_seminar_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='nr',
            field=models.IntegerField(),
        ),
    ]
