# Generated by Django 4.1.1 on 2022-09-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0008_alter_seminar_nr'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='nr',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
