# Generated by Django 4.1.1 on 2022-09-23 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0011_remove_activity_end_time_remove_activity_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='college.day'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_hour',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_hour',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='college.subject'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
