# Generated by Django 4.1.1 on 2022-09-23 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0012_alter_activity_day_alter_activity_end_hour_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['start_hour']},
        ),
    ]
