# Generated by Django 4.1.1 on 2022-09-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0013_alter_activity_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={},
        ),
        migrations.RemoveField(
            model_name='course',
            name='day',
        ),
        migrations.RemoveField(
            model_name='course',
            name='week',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='day',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='week',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='day',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='week',
        ),
        migrations.AddField(
            model_name='activity',
            name='room',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
