# Generated by Django 4.1.1 on 2022-09-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0015_course_nr'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='week',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='day',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
