# Generated by Django 4.1.1 on 2022-10-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0016_activity_week_alter_activity_day_delete_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
