# Generated by Django 4.1.1 on 2022-10-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0019_remove_document_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='activity_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
