# Generated by Django 4.1.1 on 2022-10-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0020_alter_document_activity_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='activity_id',
        ),
        migrations.AddField(
            model_name='document',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
