# Generated by Django 4.1.1 on 2022-10-03 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('college', '0021_remove_document_activity_id_document_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
