# Generated by Django 4.1.1 on 2022-10-03 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0023_alter_document_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
    ]
