# Generated by Django 4.1.1 on 2022-10-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0029_alter_exam_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
