# Generated by Django 4.1.1 on 2022-10-17 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0030_exam_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='points_earned',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(models.PositiveSmallIntegerField(default=1)), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='exam',
            name='points',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
