# Generated by Django 4.1.1 on 2022-10-30 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0031_exam_points_earned_alter_exam_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='points_earned',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(models.PositiveSmallIntegerField(default=1), 'Please enter a value lower or equal to the maximum points!'), django.core.validators.MinValueValidator(0, 'Please enter a positive number!')]),
        ),
    ]
