# Generated by Django 4.1.1 on 2022-10-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0032_alter_exam_points_earned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='points_earned',
            field=models.IntegerField(default=0),
        ),
    ]
