# Generated by Django 4.1.1 on 2022-10-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0033_alter_exam_points_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='points_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lab',
            name='points_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seminar',
            name='points_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='points_earned',
            field=models.IntegerField(default=0),
        ),
    ]
